# Generated by Django 3.1.7 on 2021-05-17 11:19

from django.db import migrations
import shortuuidfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='unid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=uuid.uuid4, editable=False, max_length=22),
        ),
    ]
