# Generated by Django 3.1.7 on 2021-05-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='assign_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'ACTIVE'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver'),
        ),
    ]
