# Generated by Django 3.1.7 on 2021-05-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210517_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='unid',
            field=models.CharField(default='6fcdee48', max_length=10),
        ),
    ]
