# Generated by Django 3.1.7 on 2021-05-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210517_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='unid',
        ),
    ]
