# Generated by Django 3.1.7 on 2021-05-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_driver_unid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='User_Id',
        ),
    ]
